### ISSUE TITLE
Improve CodeCoverage reporting for extension

### ISSUE THREAD

**Issue by trontrytel** [CliMA/CloudMicrophysics.jl#347]
Maybe something like here: https://docs.codecov.com/docs/components

```
component_management:
  individual_components:
    - component_id: src  # this is an identifier that should not be changed
      name: src  # this is a display name, and can be changed freely
      paths:
        - src/
    - component_id: ext  # this is an identifier that should not be changed
      name: ext  # this is a display name, and can be changed freely
      paths:
        - ext/
```
